name: CICD

on:
  push:
    branches:
    - master
    - develop
    - CVE-2022-22963
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install GO
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.1' # The Go version to download (if necessary) and use.

    - name: Build
      run: go build .

    - name: Lint
      run: |
        go vet .

    - name: Run tests
      run: go test ./...
